### ISSUE TITLE
getUserFeed Dont Work?

### ISSUE THREAD

**Issue by JuliusDesign** [adrianengine/jquery-spectragram#16]
Hi Adrian!

I try your code, but the "getUserFeed" dont Work =(

File > https://www.dropbox.com/s/pfb56sgax6autg9/demo.html

What is wrong? Thank you for your time.

JD

**Comment by adrianengine** [comment]
Hi! Sorry for the late response. There is a new version of the library, get it from the [releases page](/adrianengine/jquery-spectragram/releases), maybe with this one that error was fixed. Thanks!
