### ISSUE TITLE
Uncaught TypeError: Cannot read property 'accessToken' of undefined

### ISSUE THREAD

**Issue by damiansmith86** [adrianengine/jquery-spectragram#21]
I get this error in the console:

Uncaught TypeError: Cannot read property 'accessToken' of undefined
i.getUserFeed
(anonymous function)
x.extend.each
x.fn.x.each
jQuery.fn.spectragram 
(anonymous function)
c
p.fireWith
x.extend.ready
q

Here is the site:
http://charity-walk.co.uk

**Comment by WalteerW** [comment]
Hi!

I have the following error in the console:

Uncaught TypeError: Cannot read property 'length' of undefined

on line 58 of file spectragram.js

Could you help me please. Thank you

**Comment by adrianengine** [comment]
Hi Guys! Sorry for the late response. There is a new version of the library, get it from the [releases page](/adrianengine/jquery-spectragram/releases), maybe with this one that error was fixed. Thanks!
