### ISSUE TITLE
Possible to display photos from multiple accounts?

### ISSUE THREAD

**Issue by dryke-chris** [adrianengine/jquery-spectragram#22]
I have a client uses has an Instagram feed on the front page of their web site and now wants to be able to feed photos from multiple Instagram users. Is this possible?

**Comment by adrianengine** [comment]
Sorry for the very late response!
Yes it's possible:

```
$('.my-container').spectragram('getUserFeed',{
	query: 'youraccount'
});
$('.my-container').spectragram('getUserFeed',{
	query: 'yoursecondaccount'
});
```
