### ISSUE TITLE
Update on more than 20 images?

### ISSUE THREAD

**Issue by seal62** [adrianengine/jquery-spectragram#24]
Hi,

I am using your plugin (which is awesome btw) for a site I am building. I have seen that people have been asking you about loading more than 20 images at a time but this was about a year a go.

I was wondering if you have an update on this at all?

Thanks.

**Comment by codepiX-dev** [comment]
+1

**Comment by adrianengine** [comment]
Hi! thanks for your kind words!
I'm aware of this problem, but it is a restriction from the instagram API.
