### ISSUE TITLE
Uncaught TypeError: Cannot read property 'text' of null 

### ISSUE THREAD

**Issue by KhaledHamdy89** [adrianengine/jquery-spectragram#28]
If a picture's caption is empty this error occurs, because such case is not expected:

results.data[i].caption.text 

so if the caption is returned null this error occurs.
Thus may I suggest to put an empty title if such case would happen

**Comment by husseinsharif** [comment]
Late to this game.  The error is here, online 90 in my minified version...
`
n.$elem.append(e(n.options.wrapEachWith).append("<a title='" + t.data[o].caption.text + "' target='_blank' href='" + t.data[o].link + "'><img src='" + i + "'></img></a>"))
`
I added this before the line above to handle empty cases...
`
t.data[o].caption  = t.data[o].caption || {};
t.data[o].caption.text  = t.data[o].caption.text || " ";
`
Not the best solution, but quick and dirty.  Have fun.

**Comment by husseinsharif** [comment]
Late to this game.  The error is here, online 90 in my minified version...

`n.$elem.append(e(n.options.wrapEachWith).append("<a title='" + t.data[o].caption.text + "' target='_blank' href='" + t.data[o].link + "'><img src='" + i + "'></img></a>"))`

I added this before the line above to handle empty cases...

`t.data[o].caption  = t.data[o].caption || {};`
`t.data[o].caption.text  = t.data[o].caption.text || " ";`

Not the best solution, but quick and dirty.  Have fun.

**Comment by adrianengine** [comment]
Hi! This error is already fix on the latest version, you can get it from the [releases page](/adrianengine/jquery-spectragram/releases). Thanks!
