### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'n.data.length')

### ISSUE THREAD

**Issue by prembo** [adrianengine/jquery-spectragram#33]
The plugin has been working brilliantly for a couple of months now.  However, all of a sudden today, we're getting the following error:
> TypeError: undefined is not an object (evaluating 'n.data.length')
>      j (jquery.min.js, line 2)
>      fireWith (jquery.min.js, line 2)
>      x (jquery.min.js, line 4)
>      onreadystatechange (jquery.min.js, line 4)

The site that is experiencing the issue is [Pretty Little Clippies](http://www.PrettyLittleClippies.com.au/?utm_source=Github&utm_medium=issue&utm_campaign=spectragramissue
).  I've verified that it is occurring on multiple browsers (Chrome / Safari), and across multiple continents, eliminating any CDN / connectivity issues. 

Any idea why this might be happening all of a sudden?  Something at Instagram's end blocking API access?

Thank you.

**Comment by prembo** [comment]
I've created a JFiddle isolating just the relevant Spectragam code.  The error seems to be occurring within `getUserFeed`:
```
        getUserFeed: function () {
            var t = this,
                n = "/users/search?q=" + t.options.query + "&count=" + t.options.max + "&access_token=" + t.accessData.accessToken + "";
            t.fetch(n).done(function (n) {
                if (n.data.length) {
                    t.getRecentMedia(n.data[0].id)
                } else {
                    e.error("Spectagram.js - Error: the username " + t.options.query + " does not exist.")
                }
            })
        }
```

**Comment by prembo** [comment]
OK - I've tracked it down... it appears that for some reason the authentication access token has become invalid.  So issuing another access token sorted out the issue.  

I've made a small improvement to `getUserFeed` (see the [updated JSFiddle](http://jsfiddle.net/prembo/c707jw7a/2/)) to more explicitly indicate the authentication error:
```
        getUserFeed: function () {
            var t = this,
                n = "/users/search?q=" + t.options.query + "&count=" + t.options.max + "&access_token=" + t.accessData.accessToken + "";
            t.fetch(n).done(function (n) {
                if (n.meta.code == 200) {
                    if (n.data.length) {
                        t.getRecentMedia(n.data[0].id)
                    } else {
                        e.error("Spectagram.js - Error: the username " + t.options.query + " does not exist.")
                    }
                } else {
                    e.error("Spectagram.js - Error: (" + n.meta.error_type + "): " + n.meta.error_message)                    
                }
            })
        },
```

Of course it would be handy to check all the queries and display the errors.  Hope this helps.

**Comment by adrianengine** [comment]
Thanks, sorry for the late response.
