### ISSUE TITLE
TypeError: results.data is undefined

### ISSUE THREAD

**Issue by josm123** [adrianengine/jquery-spectragram#35]
This error began happening recently. Was working without an issue for months beforehand.

**Comment by YuriStruszczynski** [comment]
Same here. Or do we need to refresh the access token from time to time?

**Comment by adrianengine** [comment]
Hi Guys! Sorry for the late response. There is a new version of the library, get it from the [releases page](/adrianengine/jquery-spectragram/releases), maybe with this one that error was fixed. Thanks!
