### ISSUE TITLE
Request on a Fetch method. 

### ISSUE THREAD

**Issue by DavidStrada** [adrianengine/jquery-spectragram#4]
Hi, in the ajax part is there a way to trigger the fetch method after a period of time, so i can performed the instagram effect, fadeIn out on each image after x mins / sec.

**Comment by adrianengine** [comment]
There is a new version of the library, get it from the [releases page](/adrianengine/jquery-spectragram/releases), maybe you can try with the `complete` option. Check the documentation. Thanks.
