### ISSUE TITLE
Cant get my instagram feed to load

### ISSUE THREAD

**Issue by murdoc2211** [adrianengine/jquery-spectragram#40]
Hi 
I am currently employing a theme on GHOST that already has Spectagram pre loaded. I just have to change my Client Id and Access token for my feed to show. Its supposed to be that simple. 
I followed the steps mentioned on the instagram API portal, received the details, copied it into the code where client id and access_token have to be copied into, but the feed just doesnt show. 

When i revert to the default settings, the theme developers instagram feed is visible. But just not mine. 

Any help on this will be appreciated. My blog has been delayed by a week only coz i cant configure the damned instagram widget.

**Comment by adrianengine** [comment]
Hello!
Please show us the code you are using in order to give us an idea what could be the problem.

**Comment by murdoc2211** [comment]
Hi 

Thanks for your prompt reply. As you know that Ghost is based on Handlebars. There are 2 files, the jQuery, and the subsequent .hbs file. 
I am attaching both for your perusal. I will also attach the footer-default.hbs file where i plan to place the widget. 



This is from the theme documentation. The link leads to your page - http://lab.adrianquevedo.com/jquery-spectragram/ <http://lab.adrianquevedo.com/jquery-spectragram/>. 

Thanks for the help, man. 

Dhaval.

**Comment by adrianengine** [comment]
Sorry, we can get the files.

Anyway, please post the code snippets in a site like codepen.io or as a github gist.

**Comment by adrianengine** [comment]
Try another approach. Get the latest `spectragram.min.js` file from [the releases page](/adrianengine/jquery-spectragram/releases), replace your current one with the new one, and let me know if it worked.
