### ISSUE TITLE
i am not able to get my feed 

### ISSUE THREAD

**Issue by adnanakram23** [adrianengine/jquery-spectragram#43]
i have tried many times but still no success and have no idea it's not showing   here is the link for code https://jsfiddle.net/u5waey15/

**Comment by adrianengine** [comment]
Hello @adnanakram23 
Seems to be an issue with the empty `wrapEachWith` parameter value:
https://jsfiddle.net/u5waey15/1/

A cleaner version:
https://jsfiddle.net/u5waey15/2/
