### ISSUE TITLE
Problem with initialization

### ISSUE THREAD

**Issue by ArchimidisM** [adrianengine/jquery-spectragram#45]
### Expected behavior
I tried adding the code below:
`jQuery.fn.spectragram.accessData = {
    accessToken: '[your-instagram-access-token]',
    clientID: '[your-instagram-application-clientID]'
};`

### Actual behavior
The console returns the following error.

Uncaught Error: Method [object Object] does not exist on jQuery.spectragram

### Steps to reproduce this behavior

I am using jQuery version 1.13

Do you know what may be wrong?
Thanks in advance.

**Comment by adrianengine** [comment]
Hi @ArchimidisM 
In order to use the plugin you need to register an application at [Instagram Developers](http://instagram.com/developer/), get a **client_id** and recieve an **access_token**. Then you can replace it on the code you are using, like this:

```javascript
jQuery.fn.spectragram.accessData = {
    accessToken: '123456.78909.87654321234567890',
    clientID: '12345f67890e098765432546789'
};

//This code is an example doesn't work
```

See ya!

**Comment by ArchimidisM** [comment]
Dear adrianengine,
I have already registered the app however it does not seem to work.

**Comment by Zuiron** [comment]
I have same error message, and yes i have both token and clientid...

**Comment by adrianengine** [comment]
Seems weird… guys please add a JSFiddle or Codepen, so i can reproduce the error.

also check this one, where is working:

https://jsfiddle.net/u5waey15/2/

**Comment by adrianengine** [comment]
Hello! @Zuiron and @ArchimidisM 

Any news on this issue?

I've tested the plugin with jquery 2.2.2 and it works:

http://codepen.io/adrianengine/pen/ONwbmQ

Let me know how can I help you guys

**Comment by adrianengine** [comment]
Hi @nosugarsociety 
You need to pass the query with your username and the method `getUserFeed`:

```
$('.feed').spectragram('getUserFeed',{
      max: 4,
      query: 'nosugarsociety',
      wrapEachWith: '<div class="photo">'
    });
```

**Comment by nosugarsociety** [comment]
Thank you so much. @adrianengine
