### ISSUE TITLE
How to get the title of the photo?

### ISSUE THREAD

**Issue by umarfarukm** [adrianengine/jquery-spectragram#46]
Is there a way to fetch the title of the photo from instagram? That way we can add the 'Description' below/above the photo. 

Can you provide that feature?

**Comment by adrianengine** [comment]
Hello @umarfarukm !

Please check this codepen:
http://codepen.io/adrianengine/pen/ONwbmQ

The description of the photo appear on the title attribute of the anchor with the photo, you can get it from there with some creativity. (Like in the example I've provided)

Let me know if that works for you!

**Comment by umarfarukm** [comment]
Thanks. It worked! :+1:
