### ISSUE TITLE
spectragram.js:62 Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by mlenders** [adrianengine/jquery-spectragram#47]
I searched this error and any solution works for me :(

This is what im doing: https://jsfiddle.net/nbennfw9/

- Spectragram.js is correctly linked
- The accesToken and clientID in the jsfiddle are ficticious but in my real code are OK.

Whats the problem? :(

**Comment by adrianengine** [comment]
Hi @mlenders !

I'm not sure what's going on your code, but I tried your JSFiddle with a real token and ID and it worked:

https://jsfiddle.net/nbennfw9/1/

Please provide me more info to be able to help you.

**Comment by mlenders** [comment]
Hola Adrian (veo que eres de Colombia asique espero que no te importe que use aqui el español).

Pues por lo que parece es un problema con mi accessToken y/o mi clientID...

Puede ser que tenga mal configurada la aplicacion en Instragram? La tengo en SandBox mode todavia, y no se como "activarla" al modo real.

En las opciones de seguridad tengo desmarcadas las opciones "Disable implicit OAuth" y "Enforce signed requests" pero aun teniendolas marcadas no me funciona...

Gracias! :)

**Comment by adrianengine** [comment]
Hola @mlenders 

Aun no estoy familiarizado con el nuevo proceso para las aplicaciones en Instagram. Supongo que el error se debe a que aun estas en Sandbox mode.

Para activarla debes ingresar a editar tu app, llenar todos los datos y enviar la petición en la pestaña de permisos.

![instagram-submit](https://cloud.githubusercontent.com/assets/1206844/15457388/02201536-204e-11e6-8e0f-38111ab6aac6.jpg)

Espero sea de ayuda, un saludo!

**Comment by reinaris** [comment]
@adrianengine I'm having the same issue, but I can't read español :)
Can you let me know what the solution was?

**Comment by reinaris** [comment]
@adrianengine ah, it has something to do with https://github.com/adrianengine/jquery-spectragram/issues/48 I guess

**Comment by adrianengine** [comment]
Hi @reinaris 
Probably is related with the Instagram API changes, but give it a try to submit your app to be out of the sandbox mode, and let me know if it worked for you.

**Comment by adrianengine** [comment]
Hi guys, as long as you are fetching your own Instagram feeds, the plugin still works. Please read this: [How to get Instagram API access token and fix your broken feed](https://github.com/adrianengine/jquery-spectragram/wiki/How-to-get-Instagram-API-access-token-and-fix-your-broken-feed)

**Comment by nicolasguzca** [comment]
Gracias Adrian por el link, en mi caso faltaba ponerle al request `scope=public_content`
