### ISSUE TITLE
Images are not loading in recently

### ISSUE THREAD

**Issue by umarfarukm** [adrianengine/jquery-spectragram#49]
No images are loading from instagram in recently including from your website http://spectragram.js.org/

Kindly check, Please.

**Comment by robhyrkiel** [comment]
It appears Instagram has changed their API policies and this went into effect on June 1st. This is likely affecting the issues you are mentioning. 

"Any app created before Nov 17, 2015 will continue to function until June 1, 2016. On that date, the app will automatically be moved to Sandbox Mode if it wasn't approved through the review process. The previous version of our documentation is still available here."

More info: https://www.instagram.com/developer/

**Comment by robhyrkiel** [comment]
Here's some more helpful info from Instagram's API doc on how to get this working: https://www.instagram.com/developer/embedding/

**Comment by adrianengine** [comment]
Hi @robhyrkiel @umarfarukm 

I'm aware on the situation, the plugin stills works to get your own Instagram feed, you just need to renovate your access token.

Please follow the instructions in here:
https://github.com/adrianengine/jquery-spectragram/wiki/How-to-get-Instagram-API-access-token-and-fix-your-broken-feed

Let me know if that works!

**Comment by umarfarukm** [comment]
I followed the steps but 
* i can able to fetch only photos from my instagram account not other account. (getUserFeed)
* not able to fetch photos using #hashtags (getRecentTagged)

**Comment by adrianengine** [comment]
Hi @umarfarukm 
After the Instagram API changes:

1. ```getPopular``` function is broken due to the endpoint being removed.

2. You will still be able to access the last 20 media of any sandbox user that grants you permission with ```getUserFeed```and ```getRecentTagged``` using a client in sandbox mode. In other case you will have to submit your application to Instagram review with the [Scope: ```public_content```activated.](https://www.instagram.com/developer/authorization/)

Hope it helps, sorry for troubles caused.

**Comment by umarfarukm** [comment]
Thanks. I will submit for the review then!

**Comment by waynejuckts** [comment]
ahh, i was wondering. No it is still not working right now?

**Comment by sloga** [comment]
where can I "set" my access token and client ID so it is not public?
I don't understand, "Set your Instagram accessToken, clientID and the query:
jQuery.fn.spectragram.accessData = {
    accessToken: '[your-instagram-access-token]',
    clientID: '[your-instagram-application-clientID]'
};"

**Comment by gggg990** [comment]
I still don't see my instagram feed.. This is my code:

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script type="text/javascript" src="spectragram.js"></script>
<script>
var Spectra = {
  instaToken: 'xxxxxxxxxxxxxxxxxxx',
  instaID: 'xxxxxxxxxxxx',

  init: function () {
    $.fn.spectragram.accessData = {
      accessToken: this.instaToken,
      clientID: this.instaID
    };

$('.spectra').spectragram('getUserFeed',{
    query: 'hela',
    max: 10,
    size: 'big',
    wrapEachWith: '<p></p>',
    complete: alert('Done!');
});
  }
}

Spectra.init();
</script>
<div class="spectra"></div>

**Comment by antonygravett** [comment]
> In order to use the plugin you need to register an application at Instagram Developers, get a client_id and recieve an access_token.

Along with others here, I don’t understand how to implement this. I have logged into my client’s instagram account and have created a clientID, but I don’t see where to generate the access_token string.

Thank you kindly in advance for providing more detail to those of us who are not full-time developers and who now have website clients with blank web pages!  8–|

**Comment by sloga** [comment]
@antonygravett you put this in your browser and replace CLINET-ID and REDIRECT-URI from your client then it will put the token in the url string for you to copy.
https://api.instagram.com/oauth/authorize/?client_id=CLIENT-ID&redirect_uri=REDIRECT-URI&response_type=token

**Comment by gggg990** [comment]
I have the clientID and the accessToken, but my code doesn't work.. Can anyone please paste me the working example of their code?

**Comment by adrianengine** [comment]
Hi guys! have a look at this example:

http://codepen.io/adrianengine/pen/ONwbmQ

Remember that after API changes you can only fetch your own instagram feed while your application is on sandbox.

**Comment by sloga** [comment]
I do appreciate you sending the codepen example but I can't get it to work. Both IG accounts I manage are in sandbox mode as I only want to show my user feed and neither work in that codepen. I replaced ID, token and query. Thanks anyway.

**Comment by gggg990** [comment]
Codepen example works perfectly for me (sandbox mode).. Try to export it and change only the token and id..

**Comment by antonygravett** [comment]
@sloga Thank you for the code snippet. I entered my client ID and redirect URI and got the response:

`{"code": 403, "error_type": "OAuthForbiddenException", "error_message": "Implicit authentication is disabled”}`

I have my redirect URI set to http://corduroyshop.com (because I didn’t know what else to enter!), so is that perhaps the problem?

**Comment by sloga** [comment]
@antonygravett 
the re-direct uri needs to be whatever you entered in the client.

Also: go to your instagram developer page, manage clients, edit the client, then go to security tab and uncheck "disable implicit oauth"

![disable-implicit](https://cloud.githubusercontent.com/assets/1276945/16092331/3d1f8f80-32ec-11e6-9c73-2f9677ad5a79.jpg)

**Comment by antonygravett** [comment]
@sloga Thanks for jumping in again. I had tried unchecking Implocit OAuth before, but tried it again, and I still get a blank page:

http://corduroyshop.com/staging/160615-codepen/index.html

I tried regenerating the token and get the same one I got the first time. Any ideas? Here’s the .js where the vars are set:

http://corduroyshop.com/staging/160615-codepen/js/index.js

_(Again, this is using the exported codepen code)_

**Comment by sloga** [comment]
@antonygravett - I too have the same problem, blank page with the two different instagram feeds I manage. Both my feeds work with different apis but not spectragram.

**Comment by sloga** [comment]
@adrianengine - My access token has 2 more characters than yours does, not sure if this could be reason why it doesn't work?

**Comment by antonygravett** [comment]
@adrianengine Thanks for the idea, but it appears that tokens are variable in length, at least in my experience ...    8–|

**Comment by antonygravett** [comment]
@adrianengine Just FYI: I am trying to get instagram to work with another framework, over at https://github.com/potomak/jquery-instagram/issues/60. The developer has suggested StackOverflow as a way to get further help from the dev community, so I’ll report back if either of these works!

**Comment by adrianengine** [comment]
@sloga did you created a new app to get a working clientID and Token?

Please have a read at this: [How to get Instagram API access token and fix your broken feed](https://github.com/adrianengine/jquery-spectragram/wiki/How-to-get-Instagram-API-access-token-and-fix-your-broken-feed)

You can make it work! Old apps doesn't work anymore, you will need a new one.

**Comment by sloga** [comment]
@adrianengine @antonygravett - yes that worked!
https://www.instagram.com/oauth/authorize/?client_id=CLIENT-ID&redirect_uri=REDIRECT-URI&response_type=token**&scope=public_content**
--
weird, this is the url I was entering before. Guess I needed the '&scope=public_content' part!!!!
--
https://api.instagram.com/oauth/authorize/?client_id=CLIENT-ID&redirect_uri=REDIRECT-URI&response_type=token

**Comment by ostryweb-cz** [comment]
@adrianengine would you pls be so kind and show the codepen used above with getRecentTagged? because in description you say, it should work for 20 pics even in sandbox mode, however if i change getUserFeed to whatever other method of yours, nothing comes out...
thank you

**Comment by ruraldreams** [comment]
I had trouble because my version of jquery was old. The instructions in the wiki are fantastic - thank you @adrianengine

**Comment by adrianengine** [comment]
@ostryweb-cz sorry, the response returned by `getRecentTagged` will contain only media with the given tag, as expected. But instead of returning media from any public Instagram user, it will return only media that belongs to your sandbox users, restricted to the last 20 for each user.

If you want from any public instagram user, you should submit your app to Instagram.

**Comment by isoprop1974** [comment]
Hello there everyone, I have read the entire thread but i can't still get my Instagram feed to work after 1st June. In the Instagram developer's page i deleted and created a new app, following the [detailed instructions](https://github.com/adrianengine/jquery-spectragram/wiki/How-to-get-Instagram-API-access-token-and-fix-your-broken-feed) but it doesn't show images in the[ code snippet example ](http://codepen.io/adrianengine/pen/ONwbmQ). Any suggestions guys? It worked like a charme before 1st June :(

**Comment by isoprop1974** [comment]
I solved partially, now on Codepen example my feed works perfectly but it's not working on the live site, so I suppose the problem doesn't beside on my Instagram feed app. Still stuck :(

**Comment by NoLooseEnds** [comment]
I also had problems with this, but my issue was that the username consisted of some capitalized letters. When changed all to lower caps it worked.

(I hopefully saved someone a few minutes now) :)

**Comment by isoprop1974** [comment]
my username is lowercaps :(

**Comment by NoLooseEnds** [comment]
They should be lowercase. And they only work in lowercase. The only reason mine had a couple of uppercase, was that the username consists of two words, that we are used to separate with capitalized letters. 

As an example. If I had typed "MotorBoat" previously, it did not work now. When I changed to "motorboat" it did.

**Comment by NisoZakuta** [comment]
I am trying to get the pictures from Instagram, I cant make it work.
```

            <script>
jQuery.fn.spectragram.accessData = {
    accessToken: '215745091.32fbbcf.eda3a2061b564245898828ce0472fae9',
    accessId: '32fbbcf569054d9eb5e57bdb0f706aac'
};
                    $('div').spectragram({
                        query: 'converse',
                        max: 14,
                        size: 'big',
                        wrapEachWith: '<p></p>'
                    });</script>
            </div>
            <br />
            <div class="row">
                <div class="image-box">
                    <img src="img/21.png" width=250px>
                    <img src="img/22.png" width=250px>
                    <img src="img/23.png" width=250px>
                    <img src="img/24.png" width=250px>
                </div>
            </div>
        </div>
```


My code is like this. What is my mistake?

**Comment by adrianengine** [comment]
Hi @NisoZakuta, please have a look at this example:

http://codepen.io/adrianengine/pen/ONwbmQ

Remember that after API changes you can only fetch **your own instagram feed while your application is on sandbox.**

Please have a read at this: [How to get Instagram API access token and fix your broken feed](https://github.com/adrianengine/jquery-spectragram/wiki/How-to-get-Instagram-API-access-token-and-fix-your-broken-feed)

Hope it helps

**Comment by thinkingcap** [comment]
Think my issue was the jquery version - doesn't work with 1.7.2

**Comment by nanda1990** [comment]
can any one send me hash tag example with this plug-in


Thanks in Advance

**Comment by adrianengine** [comment]
@nanda1990 have a look at this example:

http://codepen.io/adrianengine/pen/ONwbmQ

Remember that after API changes you can only fetch your own instagram feed while your application is on sandbox.

**Comment by bradleylancaster** [comment]
Followed the steps and used the code from the codepen got it all working after authorizing the access token on local host. Thanks so much!
