### ISSUE TITLE
Display other users media is not supported because of new API?

### ISSUE THREAD

**Issue by surjithctly** [adrianengine/jquery-spectragram#50]
Hello,

The media of other users is no more working. Is there any workaround for this? 

Instagram doesn't allow to access the public_content scope for this usecase.

**Comment by adrianengine** [comment]
Hi @surjithctly 

You will still be able to access the last 20 media of **any sandbox user that grants you permission** with ```getUserFeed```and ```getRecentTagged``` using a client in sandbox mode.

In other case you will have to submit your application to Instagram review with the [Scope: ```public_content```activated.](https://www.instagram.com/developer/authorization/)

Hope it helps, sorry for troubles caused.

**Comment by surjithctly** [comment]
Thanks for the reply. How do I ask for the other user for the same? Do I need his client ID and access token?  

Its really hard now :(

**Comment by adrianengine** [comment]
You don't need client ID or access token, just invite the other users from the sandbox tab on edit client screen.

![screen shot 2016-06-11 at 12 33 04 pm](https://cloud.githubusercontent.com/assets/1206844/15986584/b9baf102-2fd0-11e6-8eb6-325d10db4159.png)

**Comment by surjithctly** [comment]
Ok. Thanks :+1:
