### ISSUE TITLE
images everywhere?

### ISSUE THREAD

**Issue by lakelounge** [adrianengine/jquery-spectragram#51]
Hi there, can anyone imagine why i have instagram images at every 'ul'?
I thought that the $('ul').spectragram … only affects the <ul class="spectragram" …
but at my page it seems that every ul on an page gets instagram images added … same if i use div instad of ul …
Any ideas? Thanks in advance

my code:
$('ul').spectragram('getUserFeed',{
    query: 'fuenfseenland.de',
    max: 6,
    size: 'medium',
    wrapEachWith: '<li class="fsl-instagram-feed-li"></li>'
});

**Comment by adrianengine** [comment]
Hi @lakelounge ,
Nop, if you want to only affect the class "spectragram" you have change your selector like this:

```
$('.spectragram').spectragram('getUserFeed',{
  query: 'fuenfseenland.de',
  max: 6,
  size: 'medium',
  wrapEachWith: ''
});
```

Hope it helps! see ya
