### ISSUE TITLE
Error: the username does not exist

### ISSUE THREAD

**Issue by Grawl** [adrianengine/jquery-spectragram#52]
### Expected behavior

Expect to show photos from [tibet_water](http://instagram.com/tibet_water/) profile.

### Actual behavior

Got an error: `Error: the username tibet_water does not exist`

### Steps to reproduce this behavior

Successfully got `accessToken` and `clientID` from a new registered Instagram application using redirect URI on my `localhost`, written this:

```js
$('#instagram').spectragram('getUserFeed', {
	query: 'tibet_water',
	max: 6
})
```

The issue is that I can show my own photos from [grawl](http://instagram.com/grawl/) profile if I set `query: 'grawl'`, but not other users. Nor 'facebook', nor any other. Just only one profile that I used to register Instagram application.

**Comment by Grawl** [comment]
Oops something went wrong. I reloaded my page manually and now all works.

Maybe it's because of Browsersync reloading or something. Sorry.

**Comment by vesper8** [comment]
I am getting this error as well, it works if I use the username mrareweb, but does not work if I use many other usernames.. all profiles are public and accessible via incognito page without being logged in

**Comment by adrianengine** [comment]
Hi! Please follow the following instructions:

https://github.com/adrianengine/jquery-spectragram/wiki/How-to-get-Instagram-API-access-token-and-fix-your-broken-feed

Since Instagram has changed its API, you can only show photos from users you have authorization on your application.
