### ISSUE TITLE
getRecentTagged returning limited amount of tagged images

### ISSUE THREAD

**Issue by fullhauser** [adrianengine/jquery-spectragram#53]
When using the getRecentTagged call it is only returning 4 images with the specified hashtag but the Instagram account has 10 images that use it.

Is there only a set amount of images it will work back through?

I have my code set up like this...

```
    jQuery.fn.spectragram.accessData = {
        accessToken: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        clientID: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
    };

    $('.instafeed').each(function() {
        $(this).children('ul').spectragram('getRecentTagged', {
            query: $(this).attr('data-user-name')
        });
    });
```

**Comment by adrianengine** [comment]
Sorry for the late response, can you show me a Codepen with your case?

I've tested it but see no problem yet.

**Comment by felipecorreiams** [comment]
Follow simulation of error: https://codepen.io/anon/pen/BWVrGX?editors=1010
