### ISSUE TITLE
Getting error results.data is undefined

### ISSUE THREAD

**Issue by Toccamonium** [adrianengine/jquery-spectragram#54]
Hi,
Thanks for this cool extension. I tried to use it for a website but I don't get any result. I created the access token and entered also the client ID in the parameters. But I still don't get any instagram image on my website. The access token has been created today, in the instagram BE I see the access for this website. The page is in an subdirectory, might this be the problem or is the URI wildcard for all other pages?
When you open https://www.fab-design.com/genf-autosalon-2017/index_de.html you will see the error in the console.

Thanks,
Florian

**Comment by adrianengine** [comment]
Hi!, please make sure you have follow these [instructions](https://github.com/adrianengine/jquery-spectragram/wiki/How-to-get-Instagram-API-access-token-and-fix-your-broken-feed).

Also, you could try with your Access Token and ID over this [Codepen](http://codepen.io/adrianengine/pen/ONwbmQ)

If it doesn't work, create a Codepen and let me know if I can help you with something else.

Regards
