### ISSUE TITLE
Error on getRecentTagged

### ISSUE THREAD

**Issue by felipecorreiams** [adrianengine/jquery-spectragram#55]
In browser console:

Uncaught Error: Spectragram.js - Error: the tag tbt does not have results.
    at Function.error (jquery.js:247)
    at Object.<anonymous> (spectragram.min.js:1)
    at j (jquery.js:3148)
    at Object.fireWith [as resolveWith] (jquery.js:3260)
    at x (jquery.js:9314)
    at HTMLScriptElement.b.onload.b.onreadystatechange (jquery.js:9829)

My code:
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script type="text/javascript" src="spectragram.min.js"></script>

    <script>
        $(document).ready(function() {
            var Spectra = {
              instaToken: '4581841919.e76705f.35c4e42189c14bcf89bbcb44ae10874c',
              instaID: ' e76705fa5f5a45958c6a3057ff1ee974',

              init: function () {
                $.fn.spectragram.accessData = {
                  accessToken: this.instaToken,
                  clientID: this.instaID
                };

                $('.Feed').spectragram('getRecentTagged',{
                  max: 12,
                  query: 'tbt',
                  wrapEachWith: '<div class="photo">'
                });
              }
            }

            Spectra.init();
        });
    </script>

**Comment by adrianengine** [comment]
`Uncaught Error: Spectragram.js - Error: the tag tbt does not have results.`

Seems like your user doesn't have photos tagged with #tbt

Please try with another tag. Also check the user permissions on your sandbox app, to make sure you are looking for the tag on the right user.

It seems to be working on this [Codepen example](http://codepen.io/adrianengine/pen/YNRvyV)
