### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by libeiro** [adrianengine/jquery-spectragram#57]
Hi everyone, I have this message:
Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (spectragram.min.js:1)
    at j (jquery-1.11.3.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.3.min.js:2)
    at x (jquery-1.11.3.min.js:5)
    at HTMLScriptElement.b.onload.b.onreadystatechange (jquery-1.11.3.min.js:5)

And I don't know how to fix it, What I have to do? Thks!

**Comment by adrianengine** [comment]
Hi @libeiro 

Please make sure you have followed this steps:
[How to get Instagram API access token and fix your broken feed](https://github.com/adrianengine/jquery-spectragram/wiki/How-to-get-Instagram-API-access-token-and-fix-your-broken-feed)

Also replace your accessToken, clientID and username in this Codepen to see if is working:
[Example Codepen](http://codepen.io/adrianengine/pen/YNRvyV)

If is not working save it and share it here.

Regards,
