### ISSUE TITLE
Show user name and profile image

### ISSUE THREAD

**Issue by Nadioca** [adrianengine/jquery-spectragram#59]
I installed the plugin and works fine, but I have a question, could I show the user profile image and name?

You could write me in spanish too.

thanks you

**Comment by adrianengine** [comment]
Sorry for the late response!

At this moment the library does not have that functionality, but let me know your specific use case and I can help you with a workaround to accomplish that.

I mean, do you want to show the user profile image and name under every photo, or just show the profile image and name, not the photos.

Thank you!

**Comment by thedesigncore** [comment]
Hello. Trying to get the plugin to work but keep getting an error: Uncaught TypeError: Cannot read property 'length' of undefined

Any help is appreciated.

**Comment by adrianengine** [comment]
Hi @thedesigncore 

Please make sure you have followed this steps:
[How to get Instagram API access token and fix your broken feed](https://github.com/adrianengine/jquery-spectragram/wiki/How-to-get-Instagram-API-access-token-and-fix-your-broken-feed)

Also replace your accessToken, clientID and username in this Codepen to see if is working:
[Example Codepen](http://codepen.io/adrianengine/pen/YNRvyV)

If is not working save it and share it here.

Regards,

**Comment by thedesigncore** [comment]
Thanks for your reply!

I followed all of the directions except I used http://instagram.pixelunion.net <http://instagram.pixelunion.net/> to generate the access token.

Will that not give me the same results?

- Danny

**Comment by thedesigncore** [comment]
I got it working!

Apparently http://instagram.pixelunion.net <http://instagram.pixelunion.net/> will not do the trick.

Thanks for your help and sorry to bother you.
