### ISSUE TITLE
Bootstrap for style

### ISSUE THREAD

**Issue by aida54901** [adrianengine/jquery-spectragram#60]
Hi!!! Help Please!!!

How can use bootstrap with spectragram to change the style of the images on my website?

THANKS  for your help!

**Comment by adrianengine** [comment]
Hi @aida54901 
Sorry for the late response… could you provide an example on codepen.io, please?
Basically you can do this:

```
$('div').spectragram({
	query: 'aida',
	max: 14,
	size: 'big',
	wrapEachWith: '<div class="card"></div>',
	complete: alert('Done!');
});
```

Using the `wrapEachWith` you can enclose the image in a container with any boostrap class you need.

Regards
