### ISSUE TITLE
Error account private while running the code?

### ISSUE THREAD

**Issue by BLCKPSTV** [adrianengine/jquery-spectragram#61]
Hi, 

I'm running the example and I'm getting after done! 

    `This user account is private or doesn't have any photos.`
and console saying 

Error: Spectragram.js - Error: the tag converse does not have results.

code :

/**
 * Instagram (v1.0)
 * GoToLoop (2018-Jan-17)
 * https://Forum.Processing.org/two/discussion/25961/instagram-api-p5js#Item_3
 */

"use strict";

jQuery.fn.spectragram.accessData = {
  accessToken: 'token',
  clientID: 'id'
};

function setup() {
  noCanvas();

  $(createElement('ol').elt).spectragram('getPopular');

  $(createDiv('').elt).spectragram('getRecentTagged', {
    query: 'converse',
	max: 14,
	size: 'big',
	wrapEachWith: '<p></p>',
	complete: alert('Done!')
  });
}

**Comment by adrianengine** [comment]
Hi @BLCKPSTV 

Please make sure you have followed this steps:
[How to get Instagram API access token and fix your broken feed](https://github.com/adrianengine/jquery-spectragram/wiki/How-to-get-Instagram-API-access-token-and-fix-your-broken-feed)

Also replace your accessToken, clientID and username in this Codepen to see if is working:
[Example Codepen](http://codepen.io/adrianengine/pen/YNRvyV)

If is not working save it and share it here.

Regards,

**Comment by BLCKPSTV** [comment]
@adrianengine Hi I did do the 'installation' of the token correctly.
But for a sanity check did it again. Got the code from the link and went to the Codepen example and copy pasted token + ID and just only got a blank screen with just the html line `Tagged with #matterapp in red, user feed in blue`

With you'r token and ID I see the example....

**Comment by BLCKPSTV** [comment]
Ok UPDATE: 

Something very odd happened when I tried to embedded the codepen example with my tokens. 
I got in the example of the embedding a working page with my tokens. 

First img is the regular example: 

<img width="1159" alt="screen shot 2018-01-19 at 23 24 31" src="https://user-images.githubusercontent.com/6031569/35174526-05338c20-fd70-11e7-81c8-b465e0890fc1.png">

Second picture when going to the embedding: 

<img width="1163" alt="screen shot 2018-01-19 at 23 24 16" src="https://user-images.githubusercontent.com/6031569/35174537-13a44ec0-fd70-11e7-8c0f-3c6c81f0c75d.png">

I tried my example to get the data first with following code:

sketch.js file: 

```
/**
 * Instagram (v1.0)
 * GoToLoop (2018-Jan-17)
 * https://Forum.Processing.org/two/discussion/25961/instagram-api-p5js#Item_3
 */

"use strict";

jQuery.fn.spectragram.accessData = {
  accessToken: '6911681487.c1fcbd0.76a3209e686e4550ad4ca5e72a2cf38b',
  clientID: '8c842ea901a4411a92ecb8304e16fab8'
};

function setup() {
  noCanvas();

  $(createElement('ol').elt).spectragram('getPopular');

  $(createDiv('').elt).spectragram('getRecentTagged', {
    query: 'adrianengine',
	max: 14,
	size: 'big',
	wrapEachWith: '<p></p>',
	complete: alert('Done!')
  });
}

```
HTML file: 
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0>
    <style> body {padding: 0; margin: 0;} </style>
    <script defer src=https://CDN.JSDelivr.net/npm/jquery></script>
    <script defer src=https://CDN.JSDelivr.net/npm/spectragram></script>
    <script defer src=https://CDN.JSDelivr.net/npm/p5></script>
    <script defer src=https://CDN.JSDelivr.net/npm/p5/lib/addons/p5.dom.min.js></script>

    <script defer src=sketch.js></script>

  </head>
  <body>
    <section>Tagged with #matterapp in red, user feed in blue</section>

<section class="feed"></section>
  </body>
</html>
```

Image of what I get following and console output: 

<img width="1194" alt="screen shot 2018-01-19 at 23 29 04" src="https://user-images.githubusercontent.com/6031569/35174779-e85ae1ec-fd70-11e7-9de8-e8eb4e516cb4.png">


followed by the result of pressing done: 

<img width="1186" alt="screen shot 2018-01-19 at 23 31 19" src="https://user-images.githubusercontent.com/6031569/35174807-fdff717a-fd70-11e7-93b5-e293d18152ac.png">

**Comment by adrianengine** [comment]
Remember that you need to query a username the has autohirized your app.

Please consider copy the codepen link so I can review it.

**Comment by BLCKPSTV** [comment]
Got it to work! cache or browser issues

**Comment by adrianengine** [comment]
Good to know!
