### ISSUE TITLE
Not work with new api...

### ISSUE THREAD

**Issue by Steppdroid** [adrianengine/jquery-spectragram#62]
i get this

http://prntscr.com/iac8l4

**Comment by adrianengine** [comment]
Hi @Steppdroid 

Please make sure you have followed this steps:
[How to get Instagram API access token and fix your broken feed](https://github.com/adrianengine/jquery-spectragram/wiki/How-to-get-Instagram-API-access-token-and-fix-your-broken-feed)

Remember that you can only access photos from accounts your sandboxed application on Instagram has received approves.

Also replace your accessToken, clientID and username in this Codepen to see if is working:
[Example Codepen](http://codepen.io/adrianengine/pen/YNRvyV)

If is not working save it and share it here.

Regards,

**Comment by mtt-shane** [comment]
It's definitely broken now. Check the console in the Codepen linked above. `Uncaught TypeError: Cannot read property 'length' of undefined` and the response from `https://api.instagram.com/v1/users/search?q=adrianengine&count=12&access_token=2136707.4dd19c1.d077b227b0474d80a5665236d2e90fcf&callback=jQuery22208164721009041269_1522955050391&_=1522955050392` is `
{code: 400, error_type: "APINotAllowedError", error_message: "This endpoint has been retired"}`

Is the new Instagram API going to allow for fetching the latest photos of a user?

**Comment by Jore** [comment]
Can also confirm having same issue.

**Comment by thesergeev** [comment]
I also confirm.

**Comment by lakelounge** [comment]
same problem here

**Comment by Zamm** [comment]
few endpoints are deprecated. started from 4th April:
https://www.instagram.com/developer/changelog/

**Comment by adrianengine** [comment]
Thank you all for let it me know this…
There's little I can do… I'm going to check if is possible to use some other endpoint and update the script accordingly. If not I will have to archive this project.

**Comment by mtt-shane** [comment]
Replacing spectragram.js with 1.1.0 is working for me, thanks @adrianengine !! Very much appreciated!
