### ISSUE TITLE
 Error: the username augeautogestion does not exist.

### ISSUE THREAD

**Issue by jorgeberbena** [adrianengine/jquery-spectragram#63]
### Expected behavior

Show latest post of our Instagram account augeautogestion.

### Actual behavior

Does not show nothing  on Chrome (Mozzilla and Safari worked good)
[https://imgur.com/a/bjDvb](url)

### Steps to reproduce this behavior
Load our page on Chrome [augeac.org](url)

**Comment by adrianengine** [comment]
Hi @jorgeberbena , seems like your issue has to be with another library/framework.

Also replace your accessToken, clientID and username in this Codepen to see if is working:
[Example Codepen](http://codepen.io/adrianengine/pen/YNRvyV)

If is not working save it and share it here.

Regards,
