### ISSUE TITLE
Instagram API update

### ISSUE THREAD

**Issue by mindystukken** [adrianengine/jquery-spectragram#64]
Apparently this plugin stopped working since Instagram changed their data names.

You now get the error results.data is undefined. Has there been an update/fix for this script yet?

**Comment by thgranger** [comment]
Hello, i have the same problem.. 😢

**Comment by sinnis-dev-trey** [comment]
just to let y'all know - they plan to deprecate the api in july, so looks like we have to update to the new graph api stuff. 

![image](https://user-images.githubusercontent.com/36502471/38866067-a2c0e918-4237-11e8-989a-980ae1f34f89.png)
