### ISSUE TITLE
Access token expires

### ISSUE THREAD

**Issue by WebCustoms** [adrianengine/jquery-spectragram#67]
Hello,

I'm currently using your plugin. This works great but unfortunately the access token expires after some time and I miss the steps from your wiki again and again.

What do I have to do to keep the access token permanently active?

Thank you very much for your support. 

Greetings

**Comment by adrianengine** [comment]
Hi @WebCustoms 

Sorry for the late response, we couldn't reproduce this issue. Currently on our demo page seems to be working as intended: https://codepen.io/adrianengine/pen/zWVVqx/

Please consider creating a new app from zero on https://www.instagram.com/developer/

Thanks,
