### ISSUE TITLE
hashtagged photos doesn't show

### ISSUE THREAD

**Issue by illuzii** [adrianengine/jquery-spectragram#68]
this code doesn't work - check out your example 8 and 9
$('ul').spectragram('getRecentTagged',{
	query: 'converse'
});
https://codepen.io/adrianengine/pen/zWVVqx/

**Comment by adrianengine** [comment]
Hello @illuzii,

After review this issue, I found out that Instagram has retired the endpoint.

Sorry for the trouble. I will update the library to reflect the change and remove the getRecentTagged method.

Regards,
