### ISSUE TITLE
instagram does not have photos

### ISSUE THREAD

**Issue by mikedd96** [adrianengine/jquery-spectragram#70]
### Expected behavior
website displays instagram photos

### Actual behavior
no photos displayed

### Steps to reproduce this behavior
have ran the code on your codepen and it displayed my photos, copied the js to my files and i get the error instagram does not have photos. 

if i use the cdn for spectragram.min.js i get Uncaught TypeError: Cannot read property 'length' of undefined

i have used enqued .min.js and .js scripts, and linked .min.js and .js scripts and all combinations.
I have tried 2 different instagram accounts (one worked previously) and tried multiple clients.
 Thanks for your help :)

**Comment by adrianengine** [comment]
Hello @mikedd96 ,
Can you provide us a codepen or similar to the issue?

If you are testing locally make sure you are running a local web server, just in case.

thanks,

**Comment by mikedd96** [comment]
https://codepen.io/adrianengine/pen/zWVVqx
it 100% works on codepen.

i am working with a live site. I did have it running fine on a local site and on the live site until i switched the instatoken and now neither the new instatoken or old work

**Comment by adrianengine** [comment]
Make sure you are using the latest version:
[Download Version 1.1.1](https://github.com/adrianengine/jquery-spectragram/releases/tag/1.1.1)

If still having issues, [please generate a new access_token](https://github.com/adrianengine/jquery-spectragram/wiki/How-to-get-Instagram-API-access-token-and-fix-your-broken-feed)

Also, check your app permissions:
![instagram-submit](https://cloud.githubusercontent.com/assets/1206844/15457388/02201536-204e-11e6-8e0f-38111ab6aac6.jpg)

regards,

**Comment by BigRD** [comment]
Hi Adrian, 
 Just thought id let you know the site is throwing these errors as well. See screenshot!
https://spectragram.js.org/
![Screenshot-2019-05-15-17 39](https://user-images.githubusercontent.com/17591491/57793355-08716080-7739-11e9-9259-a2e741f46451.jpg)

**Comment by adrianengine** [comment]
Plugin was updated, please refer to the new documentation.
