### ISSUE TITLE
Can not get access token

### ISSUE THREAD

**Issue by mrself** [adrianengine/jquery-spectragram#72]
### Expected behavior
When I visit API URL link as it is said in https://github.com/adrianengine/jquery-spectragram/wiki/How-to-get-Instagram-API-access-token-and-fix-your-broken-feed step 6 I expect to get api token in redirected url.

### Actual behavior
Instead, I got such response `{"error_type": "OAuthException", "code": 400, "error_message": "Invalid scope field(s): public_content"}`.

### Steps to reproduce this behavior
Just visit this link: https://www.instagram.com/oauth/authorize/?client_id=[id]&redirect_uri=http://localhost:3000&response_type=token&scope=public_content

**Comment by tijhaart** [comment]
Replace `public_content` with `basic` in the link (https://www.instagram.com/oauth/authorize/?client_id=[id]&redirect_uri=http://localhost:3000&response_type=token&scope=public_content) and you should be good to go.

**Comment by ctsstc** [comment]
That worked, seems my old token expired, but now all I get back is:

```
/**/ jQuery34106990522761596394_1577767092428({"pagination": {}, "data": [], "meta": {"code": 200}})
```
