### ISSUE TITLE
Can't register API

### ISSUE THREAD

**Issue by juan9999** [adrianengine/jquery-spectragram#73]
### Expected behavior

Hi, I tried following your guide to get an API 

https://github.com/adrianengine/jquery-spectragram/wiki/How-to-get-Instagram-API-access-token-and-fix-your-broken-feed) 

but it seems that registration is disabled. Any workarounds?

**Comment by adrianengine** [comment]
Hi @juan9999 ,

Please update the plugin and follow this instructions:

https://github.com/adrianengine/jquery-spectragram/wiki/Register-on-Instagram-Basic-Display-API-and-get-an-Access-Token

Thanks!
